version: '3.8'   

services:
  app:
    image: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
      - frontend-build:/usr/src/app/build
    ports:
      - 3000:3000
    depends_on:
      - todo-backend
    container_name: todo-frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend-build:/usr/share/nginx/html
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis:6-alpine
    container_name: todo-redis-prod
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
      - ./todo-backend/redis_data:/data

  todo-backend:
    image: todo-backend
    depends_on:
      - redis
      - mongo
    build:
      context: ./todo-backend
      dockerfile: dockerfile
    volumes:
      - ./todo-backend:/usr/src/backend
    container_name: todo-backend
    ports:
      - 5000:5000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

volumes:
  frontend-build: